flash_event_evenement:
    resource: "@FlashEventBundle/Resources/config/routing/evenement.yml"
    prefix:   /evenement

flash_event_homepage:
    path:     /hello/{name}
    defaults: { _controller: FlashEventBundle:Default:index }
