flash_event_evenement:
    resource: "@FlashEventBundle/Resources/config/routing/evenement.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

password_send:
    resource: "@FlashEventBundle/Resources/config/routing/password.yml"
    prefix: /

