flash_event:
    resource: "@FlashEventBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
     path:     /
     defaults: { _controller: "FlashEventBundle:default:index" }
