flash_event:
    resource: "@FlashEventBundle/Resources/config/routing.yml"
    prefix:   /evenement

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

password_send:
    resource: "@FlashEventBundle/Resources/config/routing/password.yml"
    prefix: /password