# src/Acme/UserBundle/Resources/config/doctrine/User.orm.yml
Flash\EventBundle\Entity\User:
    type:  entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO